### ISSUE TITLE
[Meta] Finish implementing all OpenGL functionnalities

### ISSUE THREAD

**Issue by tomaka** [tomaka/glium#1146]
- [ ] Correct transform feedback handling
 - [ ] Indexed transform feedback queries
 - [ ] Image load store (#361)
 - [ ] Vertex attributes arrays (#588)
 - [ ] Cubemap & cubemap arrays
 - [ ] Shader subroutines (#405)
 - [ ] Layered framebuffers (#570)
 - [ ] Multisample renderbuffers (#159)
 - [ ] Multiple viewports, blending, etc.
 - [ ] Multisampling parameters
 - [ ] Separate shader stages (#1129)
 - [ ] Sparse buffers
 - [ ] Sparse textures (#1079)

**Comment by HactarCE** [comment]
Multisample renderbuffers (https://github.com/glium/glium/issues/159) are now implemented, as of https://github.com/glium/glium/pull/1998.
