### ISSUE TITLE
OpenGL ES 2/3 mega-review

### ISSUE THREAD

**Issue by tomaka** [tomaka/glium#574]
The following modules must be reviewed for GLES2 and 3 compatibility:

- [x] buffer (#632)
- [x] context (#629)
- [x] debug (#576)
- [x] draw_parameters (nothing)
- [x] fbo (#650 - more or less hacky, but that's not specific to GLES)
- [x] framebuffer (nothing)
- [ ] image_format
- [x] index (nothing)
- [x] lib
- [ ] ops/blit
- [x] ops/clear (#658)
- [ ] ops/draw
- [x] ops/read
- [x] pixel_buffer (nothing)
- [x] program (partial in #638)
- [x] render_buffer (#584)
- [ ] sampler_object
- [x] sync (#659)
- [x] texture (#773)
- [ ] uniform
- [x] version
- [x] vertex (nothing)
- [ ] vertex_array_object (partial in #628 and #725)

cc #183

**Comment by tomaka** [comment]
I'm going to close this as most things have been reviewed and tests can handle the rest.
